### ISSUE TITLE
0.10.0 - path.join issue

### ISSUE THREAD

**Issue by chrismcv** [componentjs/builder.js#75]
https://github.com/component/builder.js/blob/master/lib/builder.js#L896

It seems that builder.urlPrefix can be null, and a build is yeilding 

```
path.js:204
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at f (path.js:204:15)
    at Object.filter (native)
    at exports.join (path.js:209:40)
    at rewrite (E:\Users\Chris\AppData\Roaming\npm\node_modules\component\node_modules\component-builder\lib\builder.js:898:11)
    at String.replace (native)
    at rewriteUrls (E:\Users\Chris\AppData\Roaming\npm\node_modules\component\node_modules\component-builder\lib\builder.js:902:14)
    at E:\Users\Chris\AppData\Roaming\npm\node_modules\component\node_modules\component-builder\lib\builder.js:604:28
    at fs.js:252:14
    at Object.oncomplete (fs.js:93:15)
```

To recreate:

```
component create test
cd test
component install timoxley/font-awesome
component build
```

specifying a prefix e.g. `component-build --prefix "./"` doesn't help.

Any suggestions?
cc/ @timoxley

**Comment by timoxley** [comment]
@visionmedia you may want to roll out a new version of `component(1)` since it's totally broken atm

**Comment by tj** [comment]
done
